### ISSUE TITLE
Broken link to API documentation

### ISSUE THREAD

**Issue by fulldecent** [lukemnet/blizzapi#139]
Link to Blizzard APIs at https://blizzapi.lukem.net/docs/ is broken.

---

I am looking to find this documentation because I'm curious if this library works with bnetd and War2BNE.

**Comment by lwojcik** [comment]
Hi!

Thanks for letting me know. Apparently Blizzard retired the old link while restructuring their documentation site. I fixed it on my end, it now leads to https://develop.battle.net/documentation. 

As of bnetd or War2BNE, I highly doubt current version of blizzapi is able to support them. I haven't seen any documented API endpoints for older games other than WoW Classic.
