### ISSUE TITLE
Problem with Battlenet-Namespace header and statiс or dynamic endpoints

### ISSUE THREAD

**Issue by AlexZeDim** [lukemnet/blizzapi#199]
There is a problem with `Battlenet-Namespace` header and it values, like:

-  `static-{region}`
-  `dynamic-{region}`
-  `profile-{region}`

I don't know about `SC2` and `Diablo` endpoints, but for world of warcraft this problem is very important.

As for now, the `namespace` parameter always should be defined in url or header. So the correct `query` example for world of warcraft character isn't `BnetApi.query('/wow/character/гордунни/инициатива')` but `BnetApi.query('/wow/character/гордунни/инициатива?namespace=profile-eu')` so according to that,[ I have made pull request and updated documentation](https://github.com/lukemnet/blizzapi-docs/pull/62).

But the actual problem, that different world of warcraft endpoints, have a different `namespace` types, some of them are *static*, another is *dynamic*. I am not a big fan [of such arcitecture](https://github.com/AlexZeDim/battlenet-api-wrapper/blob/master/src/wow/gameData.ts) of `battlenet-api-wrapper` that I inherit from QuadDamn, so I prefer to use `blizzapi` for my site instead, but without [the timeout](https://github.com/lukemnet/blizzapi/pull/198) and namespaces fix I can do nothing about it.

The real case starts when you are dealing with `dynamic` endpoints, especially `auctions` and `guild-roster`, as long as Blizzard makes support for [`If-Modified-Since` headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since) when you need to check have the endpoint data been modified you don't need to request for the data itself, you can add an additional header to the request and if doesn't modify on the server-side, you'll receive a 304 response. 

So, with `blizzapi` it's impossible to achieve. I can make a fork (as I usually do and made my own fix, it's not a problem) but I'd like to ask you, @lwojcik first. What architecture solution would you propose?

Something like: `query('/wow/character/гордунни/инициатива', 'if-modified-since') or anything else?

**Comment by lwojcik** [comment]
@AlexZeDim thanks for posting the issue!

I'm not familiar with WoW API and the concept of namespaces doesn't exist in SC2 endpoints, so I wasn't aware of this.

My idea is to add support for optional `options` object in `query` method so that it's possible to add custom headers and params to each API request, for example:

```js
const data = await BnetApi.query('/wow/character/gordunni/инициатива', {
   timeout: 30000,
   params: {
      // additional params to be passed with a request
   },
   headers: {
      // additional headers to be passed with a request
   }
});
```

What do you think?

**Comment by AlexZeDim** [comment]
Yea, it's an awesome idea. It solves much of my own, and any other future problems, even if Blizzard implement some new features or additional custom headers.

**Comment by AlexZeDim** [comment]
By the way, can you give an idea what file I should look for to implement such options? Is it `query.ts`  from `/helpers/bnet` ?

**Comment by lwojcik** [comment]
I'll be very brief as I have limited room for replies at the moment, but I also don't want to keep you waiting. Here goes:

* https://github.com/lukemnet/blizzapi/blob/b7427e49d45a2ae031077ef18e67d27635c4d563/src/classes/BlizzAPI.ts#L30 - aditional parameter `options` using an interface `QueryOptions` should go here

* https://github.com/lukemnet/blizzapi/blob/master/src/helpers/bnet/query.ts#L11 - I'd join the `options` object from `query` method with `AccessTokenOptions` (perhaps creating a new union type that joins `AccessTokenOptions` and `QueryOptions`?)

* https://github.com/lukemnet/blizzapi/blob/master/src/helpers/fetch/fetchFromUri.ts - support for `params` is missing + all `options` properties should be passed to axios method if they exist.

* Sample `QueryOptions` interface for `options` object:

```js
interface QueryOptions {
    timeout?: number;
    headers?: object;
    params?: object | URLSearchParams;
}
```

`options` object, as well as its properties, should be optional. For `timeout`, if no value is provided, we stick to default value of `10000`.

Let me know if that helps. Thanks!

**Comment by lwojcik** [comment]
@AlexZeDim I just published v1.2.0-beta.1 which implements support for options object as described in the posts above, it's also available in npm under `beta` tag.

However, I don't have test cases against WoW API and I'm not 100% sure if this implementation works correctly. Could you check it out and let me know if it works in your case?

Alternatively I can get the testing part done myself but I don't know where to look for test cases, as I don't play the game myself. Any ideas?

**Comment by AlexZeDim** [comment]
Well. these days I was trying to make my fork of `blizzapi`, but haven't succeeded with the `QueryOptions` class interface much. Seems that I overestimated my TS skills a bit. 

I already tested the `v1.2.0` branch by myself (not by jest,) via `yarn add blizzapi@beta` on production and it works perfectly as I should be. So I am ready to provide you all the necessary examples and documentation PR.

**Comment by AlexZeDim** [comment]
What have I checked already by myself and three most used cases for World of Warcraft endpoints are:

- `profile-eu` endpoint, *request a certain character by it's name and realm_slug*. 

It's especially important for production ready websites, like `raider.io` and so on, that the Blizzard server-side should always provide an correct answer for a polynomial time. For example if I want to know every avaliable data about a certain character I should request it's status, via `profile/wow/character/{realmSlug}/{characterName}/status `, receive a `Status:200 OK` and then request everything, that I need to know, like: 

 - Character Profile Summary via `/profile/wow/character/{realmSlug}/{characterName}`
 - Character Media Summary  via `/profile/wow/character/{realmSlug}/{characterName}/character-media`
 - *and so on...*

So, it's actually not 1 request, but one status request, and the bulk of requests via `Promise.all`, so that's why timeout params here were so important. If one of them in bulk fails not but error or promise reject, but without proper answer, the user will never receive an actual information at all.

- `dynamic-eu` endpoint, *request auction house data or guild-roster*. 

Here is a bit simple than before, we just send one query with `If-Modified-Since` param and if data was modified we receive `200 `status code with data, as usual, but.. If data was not modified, since the timestamp that was provided in the header, we receive a `304` status code.  So the axios count is an error, and will reject the request, but it's **OKAY**, it's really fine, and works exactly as it should be.
![200](https://user-images.githubusercontent.com/907696/94649216-e01dde00-02fc-11eb-9e71-c5305132521c.png)

- `statis-eu` endpoint, *request item data*. 

This one is simple. A typical plain vanilla request: `/data/wow/item/{itemId}`.

**Comment by lwojcik** [comment]
Jest tests pass 100% but I treat them with a grain of salt - all they do is testing the library against a mocked axios object and never talk to real Battle.net API. That's why I asked for some real life testing. :)

As for the docs, looks like a random hiccup on the CI's end.

Thank you very much good sir, that was super helpful!

I'll publish 1.2.0 as a production release later today.

**Comment by lwojcik** [comment]
v1.2.0 available on npm.
